package: epcqrcode 
version: '1.0.1'
author: 'Alexander Walther' 
supportpage: https://github.com/alexplusde/epcqrcode

requires:
    php:
        version: '>7.3,<9'
    redaxo: ^5.9

page:
    title: translate:epcqrcode_title
    icon: rex-icon fa-gear

pages:
    settings:
        title: translate:epcqrcode_settings
        icon: rex-icon fa-gear
        perm: admin
    docs:
        title: translate:epcqrcode_docs
        subPath: README.md 
        icon: rex-icon fa-info-circle
        itemclass: pull-right
        perm: epcqrcode[docs]

default_config:
    name: 'T. REDAXO'
    iban: 'REXXXXXXXXXXXXXXXXXXXXXX'
    bic: 'RAWRRRRRRRR'
    description: 'Spende'
